### ISSUE TITLE
tsx does not respect tsconfig path aliases?

### ISSUE THREAD

**Issue by vedantroy** [esbuild-kit/tsx#24] opened 2022-05-28 07:21 UTC
My tsconfig.json has the following:

```
    "paths": {
      "~/*": ["./app/*"]
    },
```

However, it seems like tsx doesn't take this into consideration. (E.g, I'll get file not found errors).

Is there anyway to work around this?

**Comment by hyrious** [comment] 2022-05-29 00:07
Because tsx is using esbuild transform mode as an esm loader/require.extensions to extend node.js, some features in build mode cannot be simply supported.

**Comment by zaripych** [comment] 2022-05-29 03:51
I think standard Node.js resolution mechanisms should work just fine here. I'd look at:

https://nodejs.org/api/packages.html#subpath-imports
https://nodejs.org/api/packages.html#subpath-exports

And try to leverage those. So your `exports` in `package.json` could look like this maybe?
```json
"exports": {
  ".": "./app"
}
```

I use those successfully for all my monorepo packages that have the source code within `./src/*` directory. `npx` works well with those.

**Comment by vedantroy** [comment] 2022-05-29 06:11
> Because tsx is using esbuild transform mode as an esm loader/require.extensions to extend node.js, some features in build mode cannot be simply supported.

Got it. It might be nice to add a note of this in the README to save future readers some time.

**Comment by privatenumber** [comment] 2022-05-29 06:27
We're not constrained to rely solely on esbuild so its definitely possible to implement.

To your original post: are you referring to Node.js import maps, or TypeScript path aliasing?

Seems your title and example are talking about different things.

If it's Node.js import maps, it should already work. Please provide a minimal repro if its not working.

**Comment by vedantroy** [comment] 2022-05-29 08:57
> We're not constrained to rely solely on esbuild so its definitely possible to implement.
> 
> To your original post: are you referring to Node.js import maps, or TypeScript path aliasing?
> 
> Seems your title and example are talking about different things.
> 
> If it's Node.js import maps, it should already work. Please provide a minimal repro if its not working.

I'll add a minimal repro tomorrow. I'm referring to Typescript path aliasing, my bad.

**Comment by privatenumber** [comment] 2022-05-29 20:44
Closing as duplicate of https://github.com/esbuild-kit/tsx/issues/3

**Closed by privatenumber** 2022-05-29 20:44 UTC
Labels: duplicate
