### ISSUE TITLE
tsx doesn't stop spawning threads with node 20

### ISSUE THREAD

**Issue by samuelgozi** [esbuild-kit/tsx#232] opened 2023-05-01 21:07 UTC
### Bug description

Whether I run `tsx ./main.ts` or `node --loader tsx main.ts`, the code runs, but threads don't stop spawning until OS kills the process.

It doesn't matter which code I run as long as it stays up.
This doesn't seem to happen with node 19.

### Reproduction

```
setInterval(() => {
  process.stderr.write(`\r${performance.now()}`);
}, 1000);

```

### Environment

```shell
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.12 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - /opt/homebrew/bin/node
    npm: 9.6.4 - /opt/homebrew/bin/npm
  npmPackages:
    tsx: ^3.8.0 => 3.12.3
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by LangLangBart** [comment] 2023-05-01 21:08
- duplicate of #229 ?

**Comment by privatenumber** [comment] 2023-05-02 00:35
Yes, seems like it.

Also:
- https://github.com/nodejs/node/issues/47566
- And maybe https://github.com/nodejs/node/issues/47761

Closing as it's a Node.js bug.

**Closed by privatenumber** 2023-05-02 00:35 UTC
Labels: bug, pending triage
