### ISSUE TITLE
SyntaxError: The requested module does not provide an export named

### ISSUE THREAD

**Issue by boredland** [esbuild-kit/tsx#331] opened 2023-10-03 17:28 UTC
### Problem

I am importing from a @jsx-email package, it doesn't matter which one, receiving:

```
> tsx test.tsx

/repro-jsx-email/test.tsx:1
import { render } from "@jsx-email/render";
         ^

SyntaxError: The requested module '@jsx-email/render' does not provide an export named 'render'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

Reading earlier threads with similar issues, I suspected this to be about the "module" paths not being read and the exports field that should be used instead. From what I understood, jsx-email seems to do it the right way: https://github.com/shellscape/jsx-email/blob/main/packages/render/package.json

If they aren't I am sure they'd be happy to correct it.

### Expected behavior

The exports to be properly picked up?

### Minimal reproduction URL

https://github.com/boredland/repro-jsx-email

### Version

3.13.0

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2023-10-03 17:41
Can you remove the `node_modules` directory from the reproduction?

**Comment by boredland** [comment] 2023-10-03 18:13
> Can you remove the `node_modules` directory from the reproduction?

Done!

**Comment by privatenumber** [comment] 2023-10-04 03:44
I'm inclined to think you didn't actually test your minimal reproduction because it emits a different error:
```
$ pnpm test

> repro-jsx-email@0.1.0 test ~/Desktop/repro-jsx-email
> tsx test.tsx

~/Desktop/repro-jsx-email/test.tsx:4
  <div>
  ^


ReferenceError: React is not defined
    at <anonymous> (~/Desktop/repro-jsx-email/test.tsx:4:3)
    at Object.<anonymous> (~/Desktop/repro-jsx-email/test.tsx:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.S (~/Desktop/repro-jsx-email/node_modules/.pnpm/tsx@3.13.0/node_modules/tsx/dist/cjs/index.cjs:1:1250)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.18.0
```

Since this is a resolution bug you're reporting, I deleted the JSX and just logged `render`, and that worked fine for me.

Closing until a minimal reproduction is provided. If you're going to update it, please link to a StackBlitz repro to ensure you've run it in the same environment.

**Closed by privatenumber** 2023-10-04 03:44 UTC
Labels: bug, pending triage

**Comment by boredland** [comment] 2023-10-04 05:45
I am very sorry and have no idea how that happened.
