### ISSUE TITLE
New version doesn't work with -r flag

### ISSUE THREAD

**Issue by malekim** [esbuild-kit/tsx#144] opened 2022-11-15 14:27 UTC
### Bug description

Usually I use `tsx` with nodemon and `-r dotenv/config`. Last version blocked that possibility, because tsx -r flag is overriding -r flag from the node environment.

I would expect, that -r flag will work like it was working before.

### Reproduction

`nodemon -r dotenv/config ./main.ts`

With nodemon.json configuration:

```
{
  "ignore": [
    ".git*",
    "node_modules/**/node_modules"
  ],
  "verbose": true,
  "watch": [
    ".env",
  ],
  "execMap": {
    "ts": "tsx"
  }
}
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 112.48 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by malekim** [comment] 2022-11-15 16:14
Yes, the command like that will also produce an error:

`tsx -r dotenv/config ./main.ts` for version `^3.12.0` doesn't work, for version `3.11.0` it works perfectly.

**Comment by privatenumber** [comment] 2022-11-16 01:59
Works fine for me.

Please provide a reproduction repository link.

**Comment by moltar** [comment] 2022-11-16 11:52
I think this is the cause of our failures too, which is the same use case: `-r dotenv/config`.

Stack trace:

![screenshot-20221116T115232-mEQLAT3i](https://user-images.githubusercontent.com/491247/202173779-fd82220a-700d-4df3-aeb1-1331ed14f618.png)

**Comment by moltar** [comment] 2022-11-16 12:03
Can confirm that downgrading to `3.11.0` had resolved the error above.

**Comment by privatenumber** [comment] 2022-11-16 13:01
Can you provide a minimal reproduction? I can't help if I can't reproduce it.

**Comment by privatenumber** [comment] 2022-11-21 14:26
@moltar @malekim 
I'd like to help but I need more information. Can either of you share a reproduction?

Will have to close this otherwise.

**Comment by moltar** [comment] 2022-11-21 23:29
```sh
git clone https://github.com/moltar/tsx-exp
cd tsx-exp
npm i
npm t
```

```plain
TypeError: Cannot read properties of null (reading 'includes')
    at Function.d.default._resolveFilename (/.../tsx-exp/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:1284)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1276:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:483:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:77:3)
    at node:internal/main/run_main_module:7:1
```

**Comment by moltar** [comment] 2022-11-21 23:29
Looks like something to do with the `baseUrl`.

**Comment by privatenumber** [comment] 2022-11-22 03:19
Thanks @moltar 

@malekim Can you confirm this is the same issue you're reporting? Based on your issue, it seems you're describing a bug in flag handling.

**Closed** 2022-11-22 03:37 UTC
Labels: bug, needs reproduction, pending triage

**Comment by privatenumber** [comment] 2022-11-22 03:47
@moltar To get the fix, you can either update the cjs-loader dependency with `npm update` or simply re-install `tsx`.

**Comment by moltar** [comment] 2022-11-22 08:10
Thank you @privatenumber!!
