### ISSUE TITLE
unable to import module with default export

### ISSUE THREAD

**Issue by sushantdhiman** [esbuild-kit/tsx#245] opened 2023-05-25 06:30 UTC
### Bug description

I am trying to import a module (`react-countdown-circle-timer`) in a script using `tsx`. This module has a default export. But `tsx` gives me this error

```ts
import { CountdownCircleTimer } from "react-countdown-circle-timer";
         ^

SyntaxError: The requested module 'react-countdown-circle-timer' does not provide an export named 'CountdownCircleTimer'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)

```

### Reproduction

- Clone https://github.com/sushantdhiman/tsx-countdown
- Run `npm test`

### Environment

```shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 2.28 GB / 7.64 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.2.0 - ~/.local/share/.nvm/versions/node/v20.2.0/bin/node
    npm: 9.6.6 - ~/.local/share/.nvm/versions/node/v20.2.0/bin/npm
  npmPackages:
    tsx: ^3.12.7 => 3.12.7
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment] 2023-05-25 06:40
If it has a default export, why don't you do a default import?

**Comment by sushantdhiman** [comment] 2023-05-25 06:51
Because my codebase is also using webpack, which fails with default export

```ts
import X from 'react-countdown-circle-timer';

ERROR (webpack):

export 'default' (imported as 'X') was not found in 'react-countdown-circle-timer' (possible exports: CountdownCircleTimer, useCountdown)
```


If I do this, it fails for `tsx`

```ts
import * as X from 'react-countdown-circle-timer';

ERROR (tsx):

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
(because tsx imports it as `X.default.CountdownCircleTimer`)

```

I think `tsx` should simply work with for

```tsx
import { CountdownCircleTimer } from "react-countdown-circle-timer";
```

**Comment by sushantdhiman** [comment] 2023-05-25 07:50
**Update :-** I patched this in my codebase by using an explicit CJS import for problematic modules

```js
// cjs_export.cjs
const toggle = require('react-toggle');
const countdown = require('react-countdown-circle-timer');

module.exports.CountdownCircleTimer = countdown.CountdownCircleTimer;
module.exports.ReactToggle = toggle.default;
```

then import this cjs file in main code

```js
// index.tsx
import { CountdownCircleTimer } from 'shared/cjs_export.cjs'
```

**Comment by privatenumber** [comment] 2023-05-26 01:33
I think tsx's behavior here is technically the more correct one. If it's a default export, a default import should be used.

Do you mind adding Webpack to your repro in https://github.com/sushantdhiman/tsx-countdown to show the comparison?

I'm curious to learn more about Webpack's decision to handle exports in that manner, and if it's configurable. Or if it's because of another loader.

**Comment by sushantdhiman** [comment] 2023-05-26 06:13
I have updated repository https://github.com/sushantdhiman/tsx-countdown with webpack, here is the output on my system

```sh
> tsx-countdown@1.0.0 test
> bash test.sh


*****************************
index.ts (TypeScript / tsx)
*****************************

tsx-countdown/index.ts:1
import { CountdownCircleTimer } from "react-countdown-circle-timer";
         ^

SyntaxError: The requested module 'react-countdown-circle-timer' does not provide an export named 'CountdownCircleTimer'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)

Node.js v20.2.0

*****************************
index.ts (Webpack)
*****************************

asset index.js 94.9 KiB [emitted] (name: index) 1 related asset
2023-05-26 11:42:08: webpack compiled successfully in 297 ms
[Function: D] { displayName: 'CountdownCircleTimer' }

*****************************
index.js (ESM / node)
*****************************

tsx-countdown/index.js:1
import { CountdownCircleTimer } from "react-countdown-circle-timer";
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'CountdownCircleTimer' not found. The requested module 'react-countdown-circle-timer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-countdown-circle-timer';
const { CountdownCircleTimer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)

Node.js v20.2.0

```

**Comment by sushantdhiman** [comment] 2023-05-26 06:17
I can see `tsx` is following same pattern as `node`, but webpack fails if use default import i.e.

```index.ts
import CountdownCircleTimer from "react-countdown-circle-timer";

console.log(CountdownCircleTimer)
```

**Comment by privatenumber** [comment] 2023-05-30 05:43
I looked into this and the Webpack one is failing because `react-countdown-circle-timer` has a `module` export that Webpack is importing from:
https://github.com/vydimitrov/react-countdown-circle-timer/blob/edbd3f2343717d66baef5e5e526512019639c7e3/packages/web/package.json#L6

Whereas Node.js only reads from `main` and `exports`.

So if you remove the `module` property from `react-countdown-circle-timer/package.json`, it will work the same way on Webpack too.

That said, there are two solutions:
- Ask `react-countdown-circle-timer` if it can use the new `package.json#exports` property
- Implement reading from `module` in tsx (specifically esm-loader)


---

FYI in the future, your minimal repro can be more minimal. None of the Webpack plugins/loaders are necessary, and the `index.ts` can just be a JS file. These help with narrowing down the exact problem because more code introduces more points of investigation.

**Comment by sushantdhiman** [comment] 2023-05-30 12:27
Thank you for investigating this issue.

As per your suggestion, I think `tsx` should support `module` entry, for two reasons.

1. `esbuild` officially supports the  [`module`](https://esbuild.github.io/api/#main-fields) field
2. `exports` is still a new proposal, there are many packages that are still using `module` field

---------------------------------------

>  FYI in the future, your minimal repro can be more minimal. None of the Webpack plugins/loaders are necessary, and the index.ts can just be a JS file. These help with narrowing down the exact problem because more code introduces more points of investigation.

Yes, It could be more minimal. But It was just a reproduction code, crudely put together to demonstrate the issue.

**Comment by axefrog** [comment] 2023-06-23 19:07
This problem is hitting me right now. Any movement on this issue? My project is built incorrectly by tsx/esbuild if I specify the "module" field in my package.json, preventing me from importing any named exports (all named exports are being moved into the default export for some reason), but not specifying it makes TypeScript in VSCode think I'm working on a CommonJS project, and so it denies me access to top-level await. I can @ts-ignore those errors, but I'd prefer not to.

**Comment by boredland** [comment] 2023-10-03 15:56
I am experiencing this with my project being `"type": "module"` and importing anything from https://jsx.email: 

```
import { Button, Column } from "@jsx-email/all";
         ^

SyntaxError: The requested module '@jsx-email/all' does not provide an export named 'Button'
```

Is there anything on my side or on the part of jsx-email that could be done to fix or work around this problem?

**Comment by privatenumber** [comment] 2023-10-03 17:02
Closing as the issue was not in tsx, but rather in `react-countdown-circle-timer`.

The reason why a minimal reproduction is necessary is so I don't end up doing free debugging work like this.

@sushantdhiman The `module` property won't be supported because tsx aims for TypeScript parity (not esbuild parity).

If others have a bug to report, please file a new issue with a minimal reproduction proving the bug is in tsx.

**Closed by privatenumber** 2023-10-03 17:02 UTC
Labels: bug, pending triage
