### ISSUE TITLE
TSX Breaks with latest VueJS (3.3.2)

### ISSUE THREAD

**Issue by arpowers** [esbuild-kit/tsx#242] opened 2023-05-16 17:51 UTC
### Bug description

Filing this bug here as I don't know if the problem is with Vue or with TSX. 

Here is the reproduction (`npm run dev`) to try: https://github.com/arpowers/vite-example

Filed an issue in VueJs as well: 
https://github.com/vuejs/core/issues/8303

### Reproduction

https://github.com/arpowers/vite-example

### Environment

```shell
VueJS / Vite / Mac
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by xiaoxiangmoe** [comment] 2023-05-17 03:05
Here is a [demo: esbuild break @vue/compiler-sfc's depedency node_modules/source-map-js/lib/quick-sort.js](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImZ1bmN0aW9uIFNvcnRUZW1wbGF0ZShjb21wYXJhdG9yKSB7ICBcbiAgZnVuY3Rpb24gZG9Tb21ldGhpbmcoKSB7IFxuICB9XG4gIHJldHVybiBkb1F1aWNrU29ydDtcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGNsb25lU29ydChjb21wYXJhdG9yKSB7XG4gIGxldCB0ZW1wbGF0ZSA9IFNvcnRUZW1wbGF0ZS50b1N0cmluZygpO1xuICBsZXQgdGVtcGxhdGVGbiA9IG5ldyBGdW5jdGlvbihgcmV0dXJuICR7dGVtcGxhdGV9YCkoKTtcbiAgcmV0dXJuIHRlbXBsYXRlRm4oY29tcGFyYXRvcik7XG59In1dLFsiZXNidWlsZC5jb25maWcuanNvbiIseyJjb250ZW50Ijoie1xuICBcImZvcm1hdFwiOiBcImVzbVwiLFxuICBcImNkblVybFwiOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2XCIsXG4gIFwia2VlcE5hbWVzXCI6IHRydWVcbn0ifV1d)

**Comment by arpowers** [comment] 2023-05-19 23:08
@privatenumber seen this?

**Comment by Jackie1210** [comment] 2023-05-25 08:36
same error here

**Comment by saonan90077** [comment] 2023-05-26 01:25
same error here
mark

**Comment by privatenumber** [comment] 2023-05-26 01:28
This is a duplicate of https://github.com/esbuild-kit/tsx/issues/113 and https://github.com/esbuild-kit/tsx/issues/228 so I'm going to close this for now and track it there.

It will be fixed once tsx is updated to be more selective with which files to compile.

**Closed by privatenumber** 2023-05-26 01:28 UTC
Labels: bug, pending triage
