### ISSUE TITLE
no "exports" main defined error when working with mocha 

### ISSUE THREAD

**Issue by xichan-ms** [esbuild-kit/tsx#200] opened 2023-03-15 17:36 UTC
### Bug description

I use **mocha** to test my code with the command '**mocha -r tsx test/xxx.test.ts**', then it reports the error 'no "exports" main defined in xxx/package.json', **however**, I can find **the 'exports' defined** in xxx/package.json **indeed**.

I think it **may result from the package** https://www.npmjs.com/package/@lodestar/types, as when I remove it, everything works well, weird, is there any differences between this package and normal one? or I missed some configurations?

**related screenshots:**

<img width="831" alt="image" src="https://user-images.githubusercontent.com/26354131/225390793-82689bdd-d56a-4344-ae6e-9dd72fc5cb8d.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/26354131/225391101-ec6d2ccf-6447-4f37-a575-bd6d2d54669e.png">

### Reproduction

package.json, **noted**: if I remove "@lodestar/types" and keep other packages, it works well.

```
{
  "dependencies": {
    "@lodestar/types": "^1.5.1",
    "@chainsafe/persistent-merkle-tree": "^0.4.2",
    "chai": "^4.3.7"
  }
}

```

common.test.ts

```
import * as common from '../src/common'
import chai from 'chai']
const assert = chai.assert

describe("common test cases", function() {
    this.timeout(60000);
    it("test 23.03.15", async () => {
        let rlt = common.xxx()
   })
})
```

### Environment

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M2
    Memory: 92.06 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment] 2023-03-15 23:10
Closing until reproduction is provided.

Also note, your error is coming from Node.js. Not tsx.

**Closed by privatenumber** 2023-03-15 23:10 UTC
Labels: bug, pending triage

**Comment by xichan-ms** [comment] 2023-03-16 02:16
thanks @privatenumber, I don't think it's coming from Node.js, as I remove this target package, and it works well. is there any incompatibility or some configurations I missed?

**Comment by xichan-ms** [comment] 2023-03-16 02:26
mini reproduction: https://github.com/xichan-ms/mini_reproduce_mocha_tsx

**Comment by privatenumber** [comment] 2023-03-16 02:36
- tsx is missing as a dependency but it's necessary to indicate which version you're using.
- Is it really minimal? I feel like the code in test and the function in common.ts are extraneous

**Comment by xichan-ms** [comment] 2023-03-16 03:12
thanks, @privatenumber I add the tsx version as use global before, and also add scripts in package.json.

you can see test2 works well, but test with mocha not work. I'm wondering is there any configurations I missed?

**Comment by xichan-ms** [comment] 2023-03-16 03:14
yes, minimal, code in test uses the function "calculateBeaconHeaderRoot" defined in common.ts to test it.

**Comment by xichan-ms** [comment] 2023-03-16 08:08
hi, @privatenumber could you help to open this issue? thanks

**Comment by privatenumber** [comment] 2023-03-18 10:53
Thanks for updating the reproduction.

In the future, I kindly ask you provide a minimal reproduction when filing an issue as it would save both of us time and make our interactions smoother. Also, when I tried running your reproduction, the `mocha` dependency was missing. Please make sure things like this are working as it could be time consuming to investigate. As you know, I'm providing support for free on my personal time, so I would appreciate it if you could help me out in this way.

In your reproduction, I noticed the command that's working is `tsx`, but the one that's not working is `mocha`. Have you considered filing a bug report with `mocha`? It might be worth trying since it seems to be the source of the issue.

And your reproduction is not minimal because you're reporting a bug in loading modules, not the logic of your code. For example, the same error can be reproduced by reducing `common.test.ts` & `common.ts` to a one-liner: `import './common'`.
