### ISSUE TITLE
Wildcard asterics in package.json scripts not resolves properly for tsx --test

### ISSUE THREAD

**Issue by Mozzart88** [esbuild-kit/tsx#295] opened 2023-08-27 23:22 UTC
### Problem

Npm scripts with `tsx --test` and wildcard path does't resolved properly.

### Expected behavior

```
/
|-- src
+-- test
      |-- file.test.ts
      |-- dir1
           |-- dir2
           |       |-- file1.test.ts
           |      +-- file2.test.ts
           |-- file1.test.ts
           +-- file2.test.ts
```
package.json
```
{
// ...
	"scripts": {
		"start": "tsx --test test/**/*.ts"
	},
// ...
}
```
npm start
```
should search all `.ts` files in `test/` recursively.

### Minimal reproduction URL

https://github.com/Mozzart88/tsx-wildcard-in-npm-scripts-minimal-reporduction.git

### Version

3.12.7

### Node.js version

18.17.1

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2023-08-27 23:43
Duplicate of https://github.com/esbuild-kit/tsx/issues/257

**Closed by privatenumber** 2023-08-27 23:43 UTC
Labels: bug, pending triage
