### ISSUE TITLE
tsx does not use typescript source for self-references or sub path imports

### ISSUE THREAD

**Issue by everett1992** [esbuild-kit/tsx#296] opened 2023-08-30 00:09 UTC
### Problem

Subpath and self-reference imports are resolved to their literal values rather than the TypeScript source file.

```
  // package.json
  "name": "subpath-exports",
  "exports": {
    "./sub": "./dist/sub.js"
  },
  "imports": {
    "#sub": "./dist/sub.js"
  },
  ```
  
```
// src/index.ts
import "./sub.js"
import "subpath-exports/sub"
import "#sub"
```

`tsx src/index.ts` will resolve `#sub` and `subpath-exports/sub` to `./dist/sub.js`, not `./src/sub.ts`.

### Expected behavior

I would expect tsx to use the same resolution at TypeScript, which is able to remap the self-reference and subpath imports to the original TypeScript source.

### Minimal reproduction URL

https://github.com/everett1992/subpath-exports

### Version

3.12.7

### Node.js version

v18.16.0

### Package manager

npm

### Operating system

macOS

### Contributions

- [X] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by everett1992** [comment] 2023-08-30 00:18
Same bug in esbuild and vitest
https://github.com/evanw/esbuild/issues/3358
https://github.com/vitest-dev/vitest/issues/4046

**Comment by privatenumber** [comment] 2023-08-30 00:52
Closing as a duplicate of https://github.com/esbuild-kit/tsx/issues/59

**Closed by privatenumber** 2023-08-30 00:52 UTC
Labels: bug, pending triage

**Comment by b13nxx** [comment] 2023-09-08 19:23
> Closing as a duplicate of #59

@privatenumber this issue is related to package.json **imports**. is it really a duplicate of the that issue?

**Comment by privatenumber** [comment] 2023-10-01 00:48
Yeah, this is categorized as Node 16 resolution so one wouldn't go out without the other.
