### ISSUE TITLE
Inconsistent formatting of `new Error().stack`

### ISSUE THREAD

**Issue by mindplay-dk** [esbuild-kit/tsx#114] opened 2022-10-07 08:52 UTC
### My use-case

I've written a very simple test-framework, which uses `new Error().stack` to locate call sites in tests - like [this](https://github.com/mindplay-dk/inertion/blob/291d6a38181fdbd672afc760353b68ddad8d590f/src/harness.ts#L49-L51):

```ts
        const location = new Error().stack!
          .split("\n")[2]
          .replace(/^\s+at /, "");
```

As you can see, I rely on the formatting of the `stack` string, which has so far been consistent for me under `ts-node`, as well as with `node` without TypeScript, as well as in the browser.

### Framing the problem

With `tsx`, I found this format deviates, by including a source location and citing the source-code line. While this preamble usually appears in the console when `node` prints an unhandled error, this is not normally included in the `stack` property.

While (to my knowledge) there is technically no standard mandating any specific format, using `new Error().stack` for this purpose is currently the only widely available means we have of obtaining call sites in JS - it's therefore important this be consistent with other platforms.

### Reproduction

I've created a minimal example to demonstrate the issue:

https://github.com/mindplay-dk/tsx-bug

(Note that this reproduction cannot come in the form of a code-snippet you can copy/paste, as this issue only occurs when loading an actual module.)

To run the example, clone the repository locally, then run the `run.sh` script, which will:

1. Package `hello_a` into a tarball.
2. Install `hello_a` from the tarball as a dependency in `hello_b`.
3. Run the `test` script in `hello_b`.

The `test` script in `hello_b` will run `hello.ts`, which will call a simple function in `hello_a`:

```ts
export function run() {
  return new Error().stack;
}
```

It will print the return value from this function to the console with some delimiters:

```ts
import { run } from "hello_a";

console.log("-----");
console.log(run());
console.log("-----");
```

The **actual** output of the script is:

```
-----
/home/mindplay/workspace/tsx-bug/hello_b/node_modules/hello_a/dist/index.js:4
  return new Error().stack;
         ^

Error
    at null.run (/home/mindplay/workspace/tsx-bug/hello_b/node_modules/hello_a/dist/index.js:4:10)
    at null.<anonymous> (/home/mindplay/workspace/tsx-bug/hello_b/hello.ts:4:13)
    at Object.<anonymous> (/home/mindplay/workspace/tsx-bug/hello_b/hello.ts:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.v (/home/mindplay/workspace/tsx-bug/hello_b/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
-----
```

The **expected** output (without the preamble) would be:

```
Error
    at null.run (/home/mindplay/workspace/tsx-bug/hello_b/node_modules/hello_a/dist/index.js:4:10)
    at null.<anonymous> (/home/mindplay/workspace/tsx-bug/hello_b/hello.ts:4:13)
    at Object.<anonymous> (/home/mindplay/workspace/tsx-bug/hello_b/hello.ts:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.v (/home/mindplay/workspace/tsx-bug/hello_b/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
```

Note that this issue does not affect packages with `"type": "module"` - to demonstrate this, you can add `"type": "module"` to `hello_b/package.json` to see that the output does not have the preamble:

```
-----
Error
    at run (file:///home/mindplay/workspace/tsx-bug/hello_b/node_modules/hello_a/dist/index.mjs:2:10)
    at null.<anonymous> (/home/mindplay/workspace/tsx-bug/hello_b/hello.ts:4:13)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
-----
```

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 5.13 GB / 6.13 GB
    Container: Yes
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 8.5.5 - ~/.npm-global/bin/npm
  npmPackages:
    tsx: ^3.10.0 => 3.10.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2022-10-07 09:09
Are you basically reporting that `new Error().stack` contains text that illustrates the position of the error? Like this:
```
  return new Error().stack;
         ^
```

**Comment by mindplay-dk** [comment] 2022-10-08 09:14
Under those specific conditions, in a nutshell, yes.

It's the output you'd expect to see on a console - but it's not the return value you normally get from this API.

**Comment by privatenumber** [comment] 2022-10-08 16:06
I'm going to close this because this is a problem in Node.js rather than tsx.
tsx defers source map support to Node.js when it's available.

#### Reproduction

Create file _index.js_:
```js
console.log(new Error().stack);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQUEsUUFBUSxJQUFJLElBQUksTUFBTSxFQUFFLEtBQUsiLCJuYW1lcyI6W10sInNvdXJjZXMiOlsiL1VzZXJzL29zYW1lL0Rvd25sb2Fkcy90c3gtYnVnLW1hc3Rlci9oZWxsb19iL2Vycm9yLXN0YWNrLmpzIl0sInNvdXJjZXNDb250ZW50IjpbImNvbnNvbGUubG9nKG5ldyBFcnJvcigpLnN0YWNrKSJdfQ==
```

Use `node` to run the file:

```js
$ node index.js
Error
    at Object.<anonymous> (/index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

Use `node` to run the file with flag `--enable-source-maps`:
```js
$ node --enable-source-maps index.js
/error-stack.js:1
console.log(new Error().stack)
            ^

Error
    at Object.<anonymous> (/error-stack.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

-----

Thanks for spending the time to write a lengthly report (twice). But next time, you don't need to provide the majority of what you provided. Please just say "`new Error().stack` is inconsistent" in "Bug description" and proceed to demonstrate how. That would be easier for others to read, understand, and support you.

In this issue, sections "My use-case" and "Framing the problem" are unnecessary. Specifically, you don't need to explain how you're parsing the stack.

In your minimal reproduction, there's a lot that can be reduced. For instance, you can simply install from directory instead of adding an `npm pack` step. Or not include a dependency at all. You can also remove TypeScript to minimize the debugging surface.

Since you previously said you didn't know how to create a minimal reproduction for this, here's a sufficient reproduction:

Given a file _error-stack.js_:
```js
console.log(new Error().stack)
```

Running in `node` and `tsx` yields different values:
```js
$ node ./error-stack.js
Error
    at Object.<anonymous> (/error-stack.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

$ tsx ./error-stack.js
/error-stack.js:1
console.log(new Error().stack)
            ^

Error
    at <anonymous> (/error-stack.js:1:13)
    at Object.<anonymous> (/error-stack.js:1:30)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.v (/Users/osame/Library/pnpm/global/5/.pnpm/@esbuild-kit+cjs-loader@2.4.0/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:901)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
```

**Closed by privatenumber** 2022-10-08 16:06 UTC
Labels: bug, pending triage

**Comment by mindplay-dk** [comment] 2022-10-09 10:08
Thank you for looking into this - and thanks for the advice!

I do have a tendency to over explain things - my experience elsewhere has been that of issues getting closed for not having enough "meat" on them, not clearly explaining *why* the issue was opened.

I had no idea `node` was doing this, as I've never used `--enable-source-maps` and didn't realize that's all `tsx` was doing to enable it. I assumed there was a custom error handler or some magic to make stack-traces work with compilation and everything - nice to know that this is really just leveraging a built-in `node` feature, I had no idea.

Thanks again! (can I donate to you or to the org behind this project somewhere?)

**Comment by giseburt** [comment] 2023-03-19 18:30
For anyone else digging around and finding this issue, in my case the solution was that with `ts-node` I was using `import "source-map-support/register";`, which fixes this very issue with `ts-node` but causes it with `tsx`.

I simply removed the `import "source-map-support/register";` line and stack traces worked as expected again.

Hopefully this helps someone else. 😄
