### ISSUE TITLE
Nestjs undefined injected class method

### ISSUE THREAD

**Issue by Satont** [esbuild-kit/tsx#37] opened 2022-06-19 00:38 UTC
I got error on `appService` property:
```
TypeError: Cannot read properties of undefined (reading 'getHello')
    at AppController.getHello (/home/satont/Tests/project-name/src/app.controller.ts:10:28)
    at <anonymous> (/home/satont/Tests/project-name/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/router/router-execution-context.js:38:29)
    at InterceptorsConsumer.intercept (/home/satont/Tests/project-name/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
    at <anonymous> (/home/satont/Tests/project-name/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/router/router-execution-context.js:46:60)
    at <anonymous> (/home/satont/Tests/project-name/node_modules/.pnpm/@nestjs+core@8.4.7_fkqgj3xrohk2pflugljc4sz7ea/node_modules/@nestjs/core/router/router-proxy.js:9:23)
    at Layer.Layer.handle_request (/home/satont/Tests/project-name/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/satont/Tests/project-name/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/route.js:144:13)
    at Route.Route.dispatch (/home/satont/Tests/project-name/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/route.js:114:3)
    at Layer.Layer.handle_request (/home/satont/Tests/project-name/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/layer.js:95:5)
    at <anonymous> (/home/satont/Tests/project-name/node_modules/.pnpm/express@4.18.1/node_modules/express/lib/router/index.js:284:15)
```

When class imported via nestjs `DI` as `constructor(private readonly appService: AppService) {}`

Reproduction:
```bash
npm i -g @nestjs/cli
nest new project-name
cd project-name
pnpm install
tsx src/main.ts
curl http://localhost:3000
```

Or you can clone https://github.com/nestjs/typescript-starter, and perform latest 3 steps.

tsx version: `3.4.3`
nodejs version: `18.2.0`

Also as fact, i tested CJS and ESM, same behavior.

**Comment by privatenumber** [comment] 2022-06-19 05:08
esbuild doesn't support decorators (`emitDecoratorMetadata` in `tsconfig.json`): https://github.com/evanw/esbuild/issues/257

Closing as a duplicate of https://github.com/esbuild-kit/core-utils/issues/14

**Closed by privatenumber** 2022-06-19 05:08 UTC

**Comment by Satont** [comment] 2022-06-19 10:32
> esbuild doesn't support decorators (`emitDecoratorMetadata` in `tsconfig.json`): [evanw/esbuild#257](https://github.com/evanw/esbuild/issues/257)
> 
> Closing as a duplicate of [esbuild-kit/core-utils#14](https://github.com/esbuild-kit/core-utils/issues/14)

Ah, sorry, somehow i missed that issue.
