### ISSUE TITLE
Support resolving `./foo.js` to `./foo.ts`

### ISSUE THREAD

**Issue by gustavopch** [esbuild-kit/tsx#342] opened 2023-07-05 23:01 UTC
For some reason, to use ESM in TypeScript, to import `./foo.ts` we need to use `import foo from './foo.js'`, so `@esbuild-kit/esm-loader` should support that.

Basically, try resolving `.js` to `.ts` and `.jsx` to `.tsx`.

Related:
- https://github.com/esbuild-kit/tsx/issues/112#issuecomment-1387660627
- https://github.com/esbuild-kit/tsx/issues/135

BTW, consider distributing the library without minification. Minifying just makes it harder to debug locally and use `patch-package` while providing no benefit.

**Comment by privatenumber** [comment] 2023-11-07 03:02
Closing as a duplicate of https://github.com/esbuild-kit/tsx/issues/112

**Closed by privatenumber** 2023-11-07 03:02 UTC
Labels: resolver

**Comment by spearmootz** [comment] 2023-12-05 19:29
i am getting this error. i posted a similar comment on 112.
