### ISSUE TITLE
Order of imports and code accessing process.env not as expected

### ISSUE THREAD

**Issue by shadowspawn** [esbuild-kit/tsx#154] opened 2022-12-01 04:32 UTC
### Bug description

I ran code which implicitly relied on processing order of import statements and access to environment variables.

I expected the imports and code to be synchronous and in order in a commonjs project.

When I ran the code with `tsx` the environment variables accessed and stored during setup in other files were undefined.

(I may have incorrect assumptions about implicit global for `process` or for how TypeScript imports should be processed!)

### Reproduction

```ts
// index.cts
process.env.EXAMPLE = 'set in index.cts';
import * as imported from './import.cjs';

console.log(`Current env is ${process.env.EXAMPLE}`);
console.log(`side loaded value is ${imported.sideLoad}`);
```

```ts
// import.cts
export const sideLoad = process.env.EXAMPLE;
```

```
% npx tsx index.cts 
Current env is set in index.cts
side loaded value is undefined
```

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 251.43 MB / 40.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 6.14.10 - /usr/local/bin/npm
  npmPackages:
    tsx: ^3.12.1 => 3.12.1 
```

Tried:
- installing node 18 did not change behaviour
- adding explicit `type: "commonjs"` in `package.json`did not change behaviour

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2022-12-01 05:27
This is expected and is spec ESM behavior. Try converting to ESM and running with Node.js.

Duplicate of https://github.com/esbuild-kit/tsx/issues/146

**Closed by privatenumber** 2022-12-01 05:27 UTC
Labels: bug, pending triage

**Comment by shadowspawn** [comment] 2022-12-01 05:48
Sorry, didn't see that previous issue. (And in my real code, it is `dotenv` being used.)

My confusion was whether a CommonJS package would "just work", or would run code like it was ESM so some breakages possible. The first line made me think perhaps ESM, but the second item made me think CommonJS might "just work". Maybe some wishful thinking!

> Blazing fast on-demand TypeScript & ESM compilation
> Works in both [CommonJS and ESM packages](https://nodejs.org/api/packages.html#type)

Thanks for the reply and info.

**Comment by privatenumber** [comment] 2022-12-01 05:53
Sorry, I don't really follow what you're saying but when you write ESM code (regardless of the package type), you should expect ESM spec behavior.

**Comment by archasek** [comment] 2023-02-07 04:50
@shadowspawn hey, same problem here (`tsx` caused that). How did you overcome it?

**Comment by shadowspawn** [comment] 2023-02-07 06:46
In my case we had some code running between imports. I refactoring the code so that imports happened first and did not rely on code side-effects, _then_ code does work.

Basically treat every TypeScript import as an ESM import, because in tsx it is! (Our code was assuming that the TypeScript imports still behaved like `require`.)

**Comment by privatenumber** [comment] 2023-02-07 06:52
The mistake is in thinking there's a "TypeScript import". There isn't.

Only ESM imports or CommonJS requires.
