### ISSUE TITLE
[3.12.3] Unknown file extension ".tsx" when importing with a `?q=123` query string

### ISSUE THREAD

**Issue by hanayashiki** [esbuild-kit/tsx#186] opened 2023-02-09 05:37 UTC
### Bug description

When using `import("./component.tsx")`, `tsx` works fine importing that file. When I postfix that file with `import("./component.tsx?t=1234")` to force a refresh, node throws an error. I think it is because `tsx` fails to handle ending query strings.

### Reproduction

https://stackblitz.com/edit/node-g43r1f?file=component.tsx,index.ts,package.json,pnpm-lock.yaml

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 48.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
    Watchman: 2022.01.10.00 - /usr/local/bin/watchman
  npmPackages:
    tsx: ^3.9.0 => 3.12.3
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment] 2023-02-09 06:07
Does it work with Node.js?

**Comment by hanayashiki** [comment] 2023-02-09 15:03
> ~Does it work with Node.js and/or TypeScript?~
> 
> Works in Node.js ESM, but not in Node.js CommonJS or TypeScript: https://stackblitz.com/edit/node-oxu3gz?file=package.json,tsconfig.json,src%2Findex.mts
> 
> #### Node.js CommonJS
> * `npm run node-cjs`: Node.js CJS doesn't support queries
> 
> #### Node.js ESM
> * `npm run node-mjs`: Node.js ESM supports queries
> * `npm run tsx-node-mjs`: tsx ESM supports queries
> 
> #### TypeScript
> * `npm run tsc`: TypeScript doesn't support queries
> * `npm run tsx-ts`: tsx TypeScript doesn't support queries
> 
> Since tsx is behaving according to what they're modeled after, I'm not sure if there is a bug.
> 
> Do you mind elaborating on your use-case more? Why do you need to force a refresh of a file in Node.js? Would `tsx watch` help?

I'm building a PDF rendering service where I need to develop the backend and the React pdf renderer at the same time. The process is: React renders component to html -> Puppeteer renders html to PDF.

I need to refresh the React component instantly because I want to see the change on the PDF in real time, but I don't want to restart the whole process because restarting puppeteer is slow and expensive which slows down my development.

**Comment by privatenumber** [comment] 2023-02-09 23:08
I had a similar issue when I was using [Playwright](https://playwright.dev/).

I worked around this with https://github.com/privatenumber/playwright-start, which starts a separate and long-running browser process that my script connects to on start-up.

Closing as this is not a bug.

**Closed by privatenumber** 2023-02-09 23:08 UTC
Labels: bug, pending triage

**Comment by hanayashiki** [comment] 2023-02-10 03:52
Is this indeed because of dynamic `import` is transpiled to `require`?

**Comment by privatenumber** [comment] 2023-02-10 04:45
Not really. `require` doesn't really support queries, so even if cjs-loader strips it for you, it won't cache bust. It will give the illusion that a feature is supported when it really isn't.
