### ISSUE TITLE
tsx --test search for .js files, instead .ts

### ISSUE THREAD

**Issue by Mozzart88** [esbuild-kit/tsx#294] opened 2023-08-27 22:48 UTC
### Problem

`tsx --test` searches `.js` files rather than `.ts` files.
I have an ts-based project with ts-based unit tests. And so I expect, that `tsx --test [path]` should behaves like `node --test [path]` except would search for `.ts` files.

### Expected behavior

```
/
|-- src
      |-- file.ts
      |-- dir1
            |-- file1.ts
            +-- file2.ts
     +-- dir2
            |-- file1.ts
            +-- file2.ts
+-- test
      |-- file.test.ts
      |-- dir1
            |-- file1.test.ts
            +-- file2.test.ts
     +-- dir2
            |-- file1.test.ts
            +-- file2.test.ts
```
```
tsx --test
```
Should search for __test__ directory and recursively search __*.test.ts__ files
```
tsx --test <directory>
```
Should recursively search __*.test.ts__ files in specified directory

In both cases it search for __*.test.js__ files, like it specified in `NodeJS` documentation.

### Minimal reproduction URL

https://github.com/Mozzart88/tsx-test-minimal-reproduction.git

### Version

3.12.7

### Node.js version

18.17.1

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2023-08-27 23:42
Duplicate of https://github.com/esbuild-kit/tsx/issues/257 and https://github.com/esbuild-kit/tsx/issues/295 (your own issue?)

Next time, please search before filing an issue.

**Closed by privatenumber** 2023-08-27 23:42 UTC
Labels: bug, pending triage

**Comment by Mozzart88** [comment] 2023-08-27 23:51
In my view, these are different issues, as in #295 it's about automatic file searching, whereas in this issue, it's about resolving wildcards in the path.

**Comment by Mozzart88** [comment] 2023-08-27 23:59
In my view, these are different issues, as in #295 it's about resolving wildcards in the path, whereas in this issue, it's about automatic file searching.
