### ISSUE TITLE
DI Decorator not working properly

### ISSUE THREAD

**Issue by ParseThisCode** [esbuild-kit/tsx#203] opened 2023-03-19 07:52 UTC
### Bug description

```ts
console.log(this.service.foo());
TypeError: Cannot read properties of undefined (reading 'foo')
```

but affter compiling to js it's working as expected!

### Reproduction

```ts
class Resolver {
  static providers: { [key: string]: any } = {};

  static resolve = (token: string) => {
    let result = Object.keys(Resolver.providers).find((key) => key === token);
    return Resolver.providers[result];
  };
}

const Injectable =
  (token: string): Function =>
  (target: new () => any) => {
    return (Resolver.providers[token] = new target());
  };

const Inject = (token: string) => (target, key) => {
  Object.defineProperty(target, key, {
    get: () => Resolver.resolve(token),
    enumerable: true,
    configurable: true,
  });
};

@Injectable("Service")
class Service {
  foo = () => "foo";
}

class Class {
  @Inject("Service") service: Service;

  constructor() {
    console.log(this.service.foo());
  }
}

new Class();
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22624
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 8.40 GB / 15.65 GB
  Binaries:
    Node: 19.7.0 - ~\AppData\Local\Volta\tools\image\node\19.7.0\node.EXE
    npm: 9.6.1 - ~\AppData\Local\Volta\tools\image\npm\9.6.1\bin\npm.CMD
  npmPackages:
    tsx: ^3.12.5 => 3.12.5
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment] 2023-03-20 05:06
Duplicate of https://github.com/esbuild-kit/tsx/issues/199

**Closed by privatenumber** 2023-03-20 05:06 UTC
Labels: bug, pending triage
